# Generated by Django 3.2.25 on 2024-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='uguyg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
